name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.3"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK with obfuscation
        run: flutter build apk --obfuscate --split-debug-info=log

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Upload APK to Diawi
        run: |
          curl -F "file=@build/app/outputs/flutter-apk/app-release.apk" \
               -F "token=$DIAWI_TOKEN" \
               -F "wall_of_apps=1" \
               -F "comment=Uploaded via GitHub Actions" \
               https://upload.diawi.com/
        env:
          DIAWI_TOKEN: ${{ secrets.DIAWI_TOKEN }}